// CSV + print-to-PDF helpers
export const escapeHtml = (v: any) => {
  const s = v === null || v === undefined ? "" : String(v);
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
};
export const safeHtml = escapeHtml;

export function downloadCSV(filename: string, rows: Array<Record<string, any>>) {
  if (!rows.length) return;
  const headers = Object.keys(rows[0]);
  const escape = (v: any) => {
    const s = v === null || v === undefined ? "" : String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const csv = [headers.join(","), ...rows.map(r => headers.map(h => escape(r[h])).join(","))].join("\n");
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename.endsWith(".csv") ? filename : `${filename}.csv`;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function printToPDF(title: string, html: string) {
  const w = window.open("", "_blank", "width=900,height=700");
  if (!w) return;
  w.document.write(`<!doctype html><html><head><title>${escapeHtml(title)}</title>
  <style>
    body{font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#0f172a;padding:32px;}
    h1{font-size:22px;margin:0 0 4px;} .sub{color:#64748b;font-size:12px;margin-bottom:24px;}
    table{width:100%;border-collapse:collapse;font-size:13px;margin-top:12px;}
    th,td{padding:8px 10px;border-bottom:1px solid #e2e8f0;text-align:left;}
    th{background:#f8fafc;font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:#475569;}
    .grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px;}
    .card{border:1px solid #e2e8f0;border-radius:10px;padding:12px;}
    .label{font-size:11px;color:#64748b;text-transform:uppercase;}
    .value{font-size:20px;font-weight:700;margin-top:2px;}
    @media print{ body{padding:16px;} }
  </style></head><body>${html}
  <script>window.onload=()=>{setTimeout(()=>window.print(),250);};</script>
  </body></html>`);
  w.document.close();
}

export function tableHTML(headers: string[], rows: Array<Array<string | number>>) {
  return `<table><thead><tr>${headers.map(h=>`<th>${escapeHtml(h)}</th>`).join("")}</tr></thead>
  <tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${escapeHtml(c)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;
}

// ----------------------------------------------------------------------------
// Branded PDF exporter — gradient header, school logo, stat cards, zebra
// tables, footer w/ timestamp + page numbers. Use for all user-facing exports.
// ----------------------------------------------------------------------------

export type BrandedSection =
  | { kind: "table"; heading?: string; headers: string[]; rows: Array<Array<string | number>> }
  | { kind: "html"; html: string };

export type BrandedPDFOptions = {
  title: string;
  subtitle?: string;
  schoolName?: string;
  schoolLogo?: string | null;
  brandColor?: string; // hex, default Legacy Schools indigo
  stats?: Array<{ label: string; value: string | number; hint?: string }>;
  sections?: BrandedSection[];
  /** Raw HTML body, appended after stats + sections. Optional. */
  body?: string;
  /** Footer note (e.g. "Confidential — for parent only"). */
  footerNote?: string;
};

const sectionHTML = (s: BrandedSection) => {
  if (s.kind === "html") return s.html;
  const head = s.heading ? `<h3>${escapeHtml(s.heading)}</h3>` : "";
  return head + tableHTML(s.headers, s.rows);
};

export function exportBrandedPDF(opts: BrandedPDFOptions) {
  const brand = opts.brandColor || "#4f46e5"; // indigo-600
  const brandDark = "#3730a3";
  const w = window.open("", "_blank", "width=960,height=760");
  if (!w) return;
  const generated = new Date().toLocaleString();
  const logoTag = opts.schoolLogo
    ? `<img src="${escapeHtml(opts.schoolLogo)}" alt="" crossorigin="anonymous" />`
    : `<div class="logo-fallback">${escapeHtml((opts.schoolName || "LS").slice(0, 2).toUpperCase())}</div>`;
  const statsHTML = opts.stats?.length
    ? `<div class="stat-grid">${opts.stats.map(s => `
        <div class="stat">
          <div class="stat-label">${escapeHtml(s.label)}</div>
          <div class="stat-value">${escapeHtml(s.value)}</div>
          ${s.hint ? `<div class="stat-hint">${escapeHtml(s.hint)}</div>` : ""}
        </div>`).join("")}</div>`
    : "";
  const sectionsHTML = (opts.sections || []).map(sectionHTML).join("");
  const bodyHTML = opts.body || "";
  const footerNote = opts.footerNote || "Generated by Legacy Schools";

  w.document.write(`<!doctype html><html><head><meta charset="utf-8"/><title>${escapeHtml(opts.title)}</title>
  <style>
    :root{
      --brand:${brand};
      --brand-dark:${brandDark};
      --ink:#0f172a;
      --muted:#64748b;
      --line:#e2e8f0;
      --soft:#f8fafc;
    }
    *{box-sizing:border-box;}
    html,body{margin:0;padding:0;}
    body{font-family:'Inter',ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:var(--ink);background:#fff;}
    .page{padding:0 36px 80px;}

    /* gradient header */
    .hero{
      margin:0 -36px 24px;
      padding:28px 36px 24px;
      background:linear-gradient(135deg,var(--brand) 0%,var(--brand-dark) 100%);
      color:#fff;
      display:flex;align-items:center;gap:18px;
      border-bottom:4px solid rgba(255,255,255,.25);
    }
    .hero img,.logo-fallback{
      width:56px;height:56px;border-radius:14px;object-fit:cover;
      background:#fff;color:var(--brand);
      display:flex;align-items:center;justify-content:center;
      font-weight:800;font-size:18px;letter-spacing:.04em;
      box-shadow:0 8px 20px -8px rgba(0,0,0,.35);
    }
    .hero-text{flex:1;min-width:0;}
    .eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.14em;opacity:.85;margin-bottom:4px;}
    .hero h1{font-size:24px;margin:0 0 4px;font-weight:700;letter-spacing:-.01em;}
    .hero .sub{font-size:13px;opacity:.92;margin:0;}
    .hero-meta{text-align:right;font-size:11px;opacity:.85;line-height:1.5;}

    h3{font-size:14px;text-transform:uppercase;letter-spacing:.08em;color:var(--brand-dark);margin:26px 0 10px;font-weight:700;}

    /* stat cards */
    .stat-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:4px 0 18px;}
    .stat{
      border:1px solid var(--line);border-radius:14px;padding:14px 16px;
      background:linear-gradient(180deg,#fff,#f8fafc);
      position:relative;overflow:hidden;
    }
    .stat::before{
      content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--brand);
    }
    .stat-label{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);font-weight:600;}
    .stat-value{font-size:22px;font-weight:700;margin-top:4px;color:var(--ink);}
    .stat-hint{font-size:11px;color:var(--muted);margin-top:2px;}

    /* tables */
    table{width:100%;border-collapse:separate;border-spacing:0;font-size:12.5px;margin-top:8px;border:1px solid var(--line);border-radius:12px;overflow:hidden;}
    th,td{padding:10px 12px;text-align:left;}
    thead th{
      background:var(--brand);color:#fff;font-size:11px;
      text-transform:uppercase;letter-spacing:.06em;font-weight:600;
      border-bottom:1px solid var(--brand-dark);
    }
    tbody tr:nth-child(even) td{background:var(--soft);}
    tbody td{border-top:1px solid var(--line);color:var(--ink);}

    /* legacy compatibility for old .grid/.card/.value markup */
    .grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:4px 0 18px;}
    .card{border:1px solid var(--line);border-radius:14px;padding:14px 16px;background:linear-gradient(180deg,#fff,#f8fafc);position:relative;overflow:hidden;}
    .card::before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--brand);}
    .label{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);font-weight:600;}
    .value{font-size:22px;font-weight:700;margin-top:4px;color:var(--ink);}

    /* footer */
    .footer{
      position:fixed;left:0;right:0;bottom:0;
      padding:10px 36px;font-size:10.5px;color:var(--muted);
      border-top:1px solid var(--line);background:#fff;
      display:flex;justify-content:space-between;align-items:center;
    }
    .footer .accent{color:var(--brand-dark);font-weight:600;}

    @page{margin:14mm 0 18mm;}
    @media print{
      .page{padding:0 18mm 24mm;}
      .hero{margin:0 -18mm 18px;padding:22px 18mm 18px;}
      .footer{padding:8px 18mm;}
    }
  </style></head><body>
    <div class="page">
      <header class="hero">
        ${logoTag}
        <div class="hero-text">
          <div class="eyebrow">${escapeHtml(opts.schoolName || "Legacy Schools")}</div>
          <h1>${escapeHtml(opts.title)}</h1>
          ${opts.subtitle ? `<p class="sub">${escapeHtml(opts.subtitle)}</p>` : ""}
        </div>
        <div class="hero-meta">
          <div>${escapeHtml(generated)}</div>
          <div>Official document</div>
        </div>
      </header>
      ${statsHTML}
      ${sectionsHTML}
      ${bodyHTML}
    </div>
    <footer class="footer">
      <div><span class="accent">${escapeHtml(opts.schoolName || "Legacy Schools")}</span> · ${escapeHtml(footerNote)}</div>
      <div>${escapeHtml(generated)}</div>
    </footer>
    <script>window.onload=()=>{setTimeout(()=>window.print(),350);};</script>
  </body></html>`);
  w.document.close();
}