// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Use to verify MCP connectivity to LegacyKool.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/verify-result.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
var verify_result_default = defineTool2({
  name: "verify_result",
  title: "Verify student result slip",
  description: "Verify the authenticity of a LegacyKool result slip by its public verification UUID. Returns the published result summary or an error if the code is invalid.",
  inputSchema: {
    verification_id: z2.string().uuid().describe("The UUID printed on the result slip QR / verification link.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ verification_id }) => {
    const url = process.env.SUPABASE_URL;
    const service = process.env.SUPABASE_SERVICE_ROLE_KEY;
    if (!url || !service) {
      return {
        content: [{ type: "text", text: "Backend not configured." }],
        isError: true
      };
    }
    const admin = createClient(url, service, { auth: { persistSession: false } });
    const { data, error } = await admin.rpc("verify_result_slip", { _id: verification_id });
    if (error) {
      return {
        content: [{ type: "text", text: `Verification failed: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { result: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fiigsvxlxaqyzcvykkvw";
var mcp_default = defineMcp({
  name: "legacykool-mcp",
  title: "LegacyKool MCP",
  version: "0.1.0",
  instructions: "Tools for LegacyKool, a school management platform. Use `echo` to confirm connectivity, and `verify_result` to check whether a printed result slip (by its verification UUID) is authentic.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, verify_result_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
